name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**/*'

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.10' ]
        os: [ "windows-latest", "ubuntu-24.04" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: build wheel
        run: |
          cd flip/python
          pip install -r requirements.txt
          pip wheel .
      - uses: actions/upload-artifact@v2
        name: Upload reports
        if: always()
        with:
          name: wheel-${{ matrix.os }}-${{ github.run_id }}-${{ github.run_number }}
          path: |
            ./flip/python/*.whl
          retention-days: 10
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release binaries
        if: startsWith(github.ref, 'refs/tags/v')
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./flip/python/*.whl"]'
