name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**/*'

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.10' ]
        os: [ "windows-latest", "ubuntu-24.04" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: build wheel
        env:
          CIBW_BUILD: "cp310*amd64"
        run: |
          cd flip/python
          git apply ../../pyproject-toml.patch
          pip install cibuildwheel==2.18.1
          pip install -r requirements.txt
          python -m cibuildwheel
      - uses: actions/upload-artifact@v2
        name: Upload reports
        if: always()
        with:
          name: wheel-${{ matrix.os }}-${{ github.run_id }}-${{ github.run_number }}
          path: |
            ./flip/python/wheelhouse/*.whl
          retention-days: 10